### ISSUE TITLE
New strange behaviour from mashie today...

### ISSUE THREAD

**Issue by fsundman73** [Kaptensanders/skolmat#12]
Hi,

Thanks for this very helpful component!

Today my Home Assistant and skolmat once again got problems with Mashie. I get high cpu-usage and this error in the logs:

okt 15 12:04:48 faringe hass[82551]: OSError: [Errno 22] Invalid argument
okt 15 12:04:48 faringe hass[82551]: The above exception was the direct cause of the following exception:
okt 15 12:04:48 faringe hass[82551]: Traceback (most recent call last):
okt 15 12:04:48 faringe hass[82551]:   File "/home/homeassistant/.homeassistant/custom_components/skolmat/menu.py", line 225, in _loadMenu
okt 15 12:04:48 faringe hass[82551]:     async with aiohttp_session.get(self.url, headers=self.headers, raise_for_status=True) as response:
okt 15 12:04:48 faringe hass[82551]:   File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
okt 15 12:04:48 faringe hass[82551]:     self._resp = await self._coro
okt 15 12:04:48 faringe hass[82551]:   File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
okt 15 12:04:48 faringe hass[82551]:     conn = await self._connector.connect(
okt 15 12:04:48 faringe hass[82551]:   File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
okt 15 12:04:48 faringe hass[82551]:     proto = await self._create_connection(req, traces, timeout)
okt 15 12:04:48 faringe hass[82551]:   File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
okt 15 12:04:48 faringe hass[82551]:     _, proto = await self._create_direct_connection(req, traces, timeout)
okt 15 12:04:48 faringe hass[82551]:   File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
okt 15 12:04:48 faringe hass[82551]:     raise ClientConnectorError(req.connection_key, exc) from exc
okt 15 12:04:48 faringe hass[82551]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host mpi.mashie.com:443 ssl:default [Invalid argument]
okt 15 12:04:48 faringe hass[82551]: 2023-10-15 12:04:48.391 ERROR (MainThread) [custom_components.skolmat.menu] Failed to load mashie.com menu from https://mpi.mashie.com/public/menu/vallentuna%20kommun/10b58ecf

If I do view source of the page above in the browser. I just get this content :-(

<html><head><meta name="color-scheme" content="light dark"></head><body><div class="line-gutter-backdrop"></div><form autocomplete="off"><label class="line-wrap-control">Radbyte<input type="checkbox" aria-label="Radbyte"></label></form><table><tbody><tr><td class="line-number" value="1"></td><td class="line-content"><br></td></tr><tr><td class="line-number" value="2"></td><td class="line-content"><br></td></tr><tr><td class="line-number" value="3"></td><td class="line-content"><span class="html-tag">&lt;h2&gt;</span></td></tr><tr><td class="line-number" value="4"></td><td class="line-content">    Just nu finns det ingen matsedel att visa</td></tr><tr><td class="line-number" value="5"></td><td class="line-content"><span class="html-tag">&lt;/h2&gt;</span><span class="html-end-of-file"></span></td></tr></tbody></table></body></html>

No big issue, but maybe something to improve next time you do changes....

Best regards,
Fredrik Sundman

**Comment by Kaptensanders** [comment]
Hi Fredrik, had a look and not sure what happens to that menu. I had it in a test script and had to replace it with another mashie menu because it provided no data. In any case cpu should not go crazy. I could not reproduce. Do you get flooded with those messages in the log?

**Comment by fsundman73** [comment]
I haven´t used "skolmat" for over a year as my childrens school have stopped use Mashie as you noted. But I saw you had released a new version so I installed it and tried it with my old rss feed. The one that doesn´t contain the correct data, (an rss-feed), but instead the h2 element in my error report above.

With that in mind I still get the same errors in the log, one error every 30 seconds. I can´t say about the cpu-usage as I have switched hardware, but of course it create load to try fetch the file and create an error message over and over again.

But is it an error in your integration or just me entering a wrong feed or the school that doesn´t publish anything. Only you can decide that :-)

I still think your integration is great, I loved it. No problem if you want to close this.

Below are the error log from Home Assistant, you can see it have happend 23 times in 10 minutes....

Felet härrör från en anpassad integration.

Logger: custom_components.skolmat.menu
Källa: custom_components/skolmat/menu.py:244
integration: skolmat (dokumentation, ärenden)
Inträffade först: 20:25:27 (23 händelser)
Senast loggade: 20:36:27

Failed to retrieve https://mpi.mashie.com/public/menu/vallentuna%20kommun/10b58ecf
Traceback (most recent call last):
  File "/config/custom_components/skolmat/menu.py", line 244, in _loadMenu
    jsonData = soup.select_one("script").string
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by Kaptensanders** [comment]
yes the page does not contain any data. Oki thanks, I'll add some nicer error handling here.
