### ISSUE TITLE
Detected blocking call to open inside the event loop by custom integration 'skolmat'

### ISSUE THREAD

**Issue by johro897** [Kaptensanders/skolmat#14]
WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'skolmat' at custom_components/skolmat/menu.py, line 142: return feedparser.parse(raw_feed) (offender: /usr/local/lib/python3.12/site-packages/feedparser/api.py, line 119: with open(url_file_stream_or_string, 'rb') as f:), please create a bug report at https://github.com/Kaptensanders/skolmat/issues

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1289, in async_device_update
    await self.async_update()
  File "/config/custom_components/skolmat/sensor.py", line 84, in async_update
    bResult = await self.menu.loadMenu(async_get_clientsession(self.hass))
  File "/config/custom_components/skolmat/menu.py", line 53, in loadMenu
    await self._loadMenu(aiohttp_session)
  File "/config/custom_components/skolmat/menu.py", line 147, in _loadMenu
    menuFeed = await self._getFeed(aiohttp_session)
  File "/config/custom_components/skolmat/menu.py", line 142, in _getFeed
    return feedparser.parse(raw_feed)

**Comment by Kaptensanders** [comment]
thanks, got it too.  fixed in 1.5.1
